"""initial_schema

Revision ID: 3997a8e62d56
Revises: 
Create Date: 2026-05-22 00:25:35.303912+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3997a8e62d56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_ingrediente')
    op.drop_table('pedidos')
    op.drop_table('persons')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('contacts')
    op.drop_table('item_ingrediente_removido')
    op.drop_table('itens_pedido')
    op.drop_table('ingredientes')
    op.drop_table('produtos_cardapio')
    op.alter_column('tm_clients', 'endereco',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tm_clients', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tm_clients', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tm_clients_cpf_cnpj'), table_name='tm_clients')
    op.drop_index(op.f('idx_tm_clients_deleted_at'), table_name='tm_clients')
    op.drop_index(op.f('idx_tm_clients_nome_trgm'), table_name='tm_clients', postgresql_ops={'nome': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('tm_clients_cpf_cnpj_key'), 'tm_clients', type_='unique')
    op.create_index(op.f('ix_tm_clients_cpf_cnpj'), 'tm_clients', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_tm_clients_deleted_at'), 'tm_clients', ['deleted_at'], unique=False)
    op.alter_column('tm_drivers', 'status',
               existing_type=postgresql.ENUM('ativo', 'inativo', 'suspenso', 'ferias', name='driverstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tm_drivers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tm_drivers_cpf'), table_name='tm_drivers')
    op.drop_index(op.f('idx_tm_drivers_deleted_at'), table_name='tm_drivers')
    op.drop_index(op.f('idx_tm_drivers_user_id'), table_name='tm_drivers')
    op.drop_constraint(op.f('tm_drivers_cpf_key'), 'tm_drivers', type_='unique')
    op.create_index(op.f('ix_tm_drivers_cpf'), 'tm_drivers', ['cpf'], unique=True)
    op.create_index(op.f('ix_tm_drivers_deleted_at'), 'tm_drivers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tm_drivers_user_id'), 'tm_drivers', ['user_id'], unique=False)
    op.alter_column('tm_finance_entries', 'status',
               existing_type=postgresql.ENUM('pendente', 'pago', 'cancelado', 'vencido', name='financeentrystatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tm_finance_entries', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tm_finance_entries_deleted_at'), table_name='tm_finance_entries')
    op.drop_index(op.f('idx_tm_finance_entries_freight_id'), table_name='tm_finance_entries')
    op.drop_index(op.f('idx_tm_finance_entries_status'), table_name='tm_finance_entries')
    op.drop_index(op.f('idx_tm_finance_entries_tipo'), table_name='tm_finance_entries')
    op.create_index(op.f('ix_tm_finance_entries_categoria'), 'tm_finance_entries', ['categoria'], unique=False)
    op.create_index(op.f('ix_tm_finance_entries_deleted_at'), 'tm_finance_entries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tm_finance_entries_freight_id'), 'tm_finance_entries', ['freight_id'], unique=False)
    op.create_index(op.f('ix_tm_finance_entries_status'), 'tm_finance_entries', ['status'], unique=False)
    op.create_index(op.f('ix_tm_finance_entries_tipo'), 'tm_finance_entries', ['tipo'], unique=False)
    op.alter_column('tm_freight_attachments', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tm_freight_attachments', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tm_freight_attachments_freight_id'), table_name='tm_freight_attachments')
    op.create_index(op.f('ix_tm_freight_attachments_freight_id'), 'tm_freight_attachments', ['freight_id'], unique=False)
    op.alter_column('tm_freight_costs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tm_freight_costs_freight_id'), table_name='tm_freight_costs')
    op.create_index(op.f('ix_tm_freight_costs_freight_id'), 'tm_freight_costs', ['freight_id'], unique=False)
    op.alter_column('tm_freights', 'origem',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('tm_freights', 'destino',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('tm_freights', 'status',
               existing_type=postgresql.ENUM('orcamento', 'confirmado', 'em_coleta', 'em_transporte', 'entregue', 'cancelado', name='freightstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tm_freights', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tm_freights_client_id'), table_name='tm_freights')
    op.drop_index(op.f('idx_tm_freights_deleted_at'), table_name='tm_freights')
    op.drop_index(op.f('idx_tm_freights_driver_id'), table_name='tm_freights')
    op.drop_index(op.f('idx_tm_freights_status'), table_name='tm_freights')
    op.drop_index(op.f('idx_tm_freights_truck_id'), table_name='tm_freights')
    op.create_index(op.f('ix_tm_freights_client_id'), 'tm_freights', ['client_id'], unique=False)
    op.create_index(op.f('ix_tm_freights_deleted_at'), 'tm_freights', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tm_freights_driver_id'), 'tm_freights', ['driver_id'], unique=False)
    op.create_index(op.f('ix_tm_freights_status'), 'tm_freights', ['status'], unique=False)
    op.create_index(op.f('ix_tm_freights_truck_id'), 'tm_freights', ['truck_id'], unique=False)
    op.alter_column('tm_maintenance', 'status',
               existing_type=postgresql.ENUM('agendada', 'em_andamento', 'concluida', 'cancelada', name='maintenancestatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tm_maintenance', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tm_maintenance_deleted_at'), table_name='tm_maintenance')
    op.drop_index(op.f('idx_tm_maintenance_status'), table_name='tm_maintenance')
    op.drop_index(op.f('idx_tm_maintenance_truck_id'), table_name='tm_maintenance')
    op.create_index(op.f('ix_tm_maintenance_deleted_at'), 'tm_maintenance', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tm_maintenance_truck_id'), 'tm_maintenance', ['truck_id'], unique=False)
    op.alter_column('tm_refresh_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tm_refresh_tokens_token_hash'), table_name='tm_refresh_tokens')
    op.drop_index(op.f('idx_tm_refresh_tokens_user_id'), table_name='tm_refresh_tokens')
    op.drop_constraint(op.f('tm_refresh_tokens_token_hash_key'), 'tm_refresh_tokens', type_='unique')
    op.create_index(op.f('ix_tm_refresh_tokens_token_hash'), 'tm_refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_tm_refresh_tokens_user_id'), 'tm_refresh_tokens', ['user_id'], unique=False)
    op.alter_column('tm_tracking_updates', 'evento_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tm_tracking_updates', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tm_tracking_updates_evento_at'), table_name='tm_tracking_updates')
    op.drop_index(op.f('idx_tm_tracking_updates_freight_id'), table_name='tm_tracking_updates')
    op.create_index(op.f('ix_tm_tracking_updates_freight_id'), 'tm_tracking_updates', ['freight_id'], unique=False)
    op.alter_column('tm_trucks', 'km_atual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tm_trucks', 'status',
               existing_type=postgresql.ENUM('disponivel', 'em_viagem', 'em_manutencao', 'inativo', name='truckstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tm_trucks', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tm_trucks_deleted_at'), table_name='tm_trucks')
    op.drop_index(op.f('idx_tm_trucks_placa'), table_name='tm_trucks')
    op.drop_index(op.f('idx_tm_trucks_status'), table_name='tm_trucks')
    op.drop_constraint(op.f('tm_trucks_placa_key'), 'tm_trucks', type_='unique')
    op.create_index(op.f('ix_tm_trucks_deleted_at'), 'tm_trucks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tm_trucks_placa'), 'tm_trucks', ['placa'], unique=True)
    op.alter_column('tm_users', 'role',
               existing_type=postgresql.ENUM('admin', 'operador', 'financeiro', 'motorista', name='userrole'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tm_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tm_users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tm_users_deleted_at'), table_name='tm_users')
    op.drop_index(op.f('idx_tm_users_email'), table_name='tm_users')
    op.drop_constraint(op.f('tm_users_email_key'), 'tm_users', type_='unique')
    op.create_index(op.f('ix_tm_users_deleted_at'), 'tm_users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tm_users_email'), 'tm_users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tm_users_email'), table_name='tm_users')
    op.drop_index(op.f('ix_tm_users_deleted_at'), table_name='tm_users')
    op.create_unique_constraint(op.f('tm_users_email_key'), 'tm_users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tm_users_email'), 'tm_users', ['email'], unique=False)
    op.create_index(op.f('idx_tm_users_deleted_at'), 'tm_users', ['deleted_at'], unique=False)
    op.alter_column('tm_users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('tm_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('tm_users', 'role',
               existing_type=postgresql.ENUM('admin', 'operador', 'financeiro', 'motorista', name='userrole'),
               server_default=sa.text("'operador'::userrole"),
               existing_nullable=False)
    op.drop_index(op.f('ix_tm_trucks_placa'), table_name='tm_trucks')
    op.drop_index(op.f('ix_tm_trucks_deleted_at'), table_name='tm_trucks')
    op.create_unique_constraint(op.f('tm_trucks_placa_key'), 'tm_trucks', ['placa'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tm_trucks_status'), 'tm_trucks', ['status'], unique=False)
    op.create_index(op.f('idx_tm_trucks_placa'), 'tm_trucks', ['placa'], unique=False)
    op.create_index(op.f('idx_tm_trucks_deleted_at'), 'tm_trucks', ['deleted_at'], unique=False)
    op.alter_column('tm_trucks', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('tm_trucks', 'status',
               existing_type=postgresql.ENUM('disponivel', 'em_viagem', 'em_manutencao', 'inativo', name='truckstatus'),
               server_default=sa.text("'disponivel'::truckstatus"),
               existing_nullable=False)
    op.alter_column('tm_trucks', 'km_atual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_tm_tracking_updates_freight_id'), table_name='tm_tracking_updates')
    op.create_index(op.f('idx_tm_tracking_updates_freight_id'), 'tm_tracking_updates', ['freight_id'], unique=False)
    op.create_index(op.f('idx_tm_tracking_updates_evento_at'), 'tm_tracking_updates', ['evento_at'], unique=False)
    op.alter_column('tm_tracking_updates', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('tm_tracking_updates', 'evento_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_tm_refresh_tokens_user_id'), table_name='tm_refresh_tokens')
    op.drop_index(op.f('ix_tm_refresh_tokens_token_hash'), table_name='tm_refresh_tokens')
    op.create_unique_constraint(op.f('tm_refresh_tokens_token_hash_key'), 'tm_refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tm_refresh_tokens_user_id'), 'tm_refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_tm_refresh_tokens_token_hash'), 'tm_refresh_tokens', ['token_hash'], unique=False)
    op.alter_column('tm_refresh_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_tm_maintenance_truck_id'), table_name='tm_maintenance')
    op.drop_index(op.f('ix_tm_maintenance_deleted_at'), table_name='tm_maintenance')
    op.create_index(op.f('idx_tm_maintenance_truck_id'), 'tm_maintenance', ['truck_id'], unique=False)
    op.create_index(op.f('idx_tm_maintenance_status'), 'tm_maintenance', ['status'], unique=False)
    op.create_index(op.f('idx_tm_maintenance_deleted_at'), 'tm_maintenance', ['deleted_at'], unique=False)
    op.alter_column('tm_maintenance', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('tm_maintenance', 'status',
               existing_type=postgresql.ENUM('agendada', 'em_andamento', 'concluida', 'cancelada', name='maintenancestatus'),
               server_default=sa.text("'agendada'::maintenancestatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_tm_freights_truck_id'), table_name='tm_freights')
    op.drop_index(op.f('ix_tm_freights_status'), table_name='tm_freights')
    op.drop_index(op.f('ix_tm_freights_driver_id'), table_name='tm_freights')
    op.drop_index(op.f('ix_tm_freights_deleted_at'), table_name='tm_freights')
    op.drop_index(op.f('ix_tm_freights_client_id'), table_name='tm_freights')
    op.create_index(op.f('idx_tm_freights_truck_id'), 'tm_freights', ['truck_id'], unique=False)
    op.create_index(op.f('idx_tm_freights_status'), 'tm_freights', ['status'], unique=False)
    op.create_index(op.f('idx_tm_freights_driver_id'), 'tm_freights', ['driver_id'], unique=False)
    op.create_index(op.f('idx_tm_freights_deleted_at'), 'tm_freights', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_tm_freights_client_id'), 'tm_freights', ['client_id'], unique=False)
    op.alter_column('tm_freights', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('tm_freights', 'status',
               existing_type=postgresql.ENUM('orcamento', 'confirmado', 'em_coleta', 'em_transporte', 'entregue', 'cancelado', name='freightstatus'),
               server_default=sa.text("'orcamento'::freightstatus"),
               existing_nullable=False)
    op.alter_column('tm_freights', 'destino',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('tm_freights', 'origem',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_tm_freight_costs_freight_id'), table_name='tm_freight_costs')
    op.create_index(op.f('idx_tm_freight_costs_freight_id'), 'tm_freight_costs', ['freight_id'], unique=False)
    op.alter_column('tm_freight_costs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_tm_freight_attachments_freight_id'), table_name='tm_freight_attachments')
    op.create_index(op.f('idx_tm_freight_attachments_freight_id'), 'tm_freight_attachments', ['freight_id'], unique=False)
    op.alter_column('tm_freight_attachments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('tm_freight_attachments', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'comprovante'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_tm_finance_entries_tipo'), table_name='tm_finance_entries')
    op.drop_index(op.f('ix_tm_finance_entries_status'), table_name='tm_finance_entries')
    op.drop_index(op.f('ix_tm_finance_entries_freight_id'), table_name='tm_finance_entries')
    op.drop_index(op.f('ix_tm_finance_entries_deleted_at'), table_name='tm_finance_entries')
    op.drop_index(op.f('ix_tm_finance_entries_categoria'), table_name='tm_finance_entries')
    op.create_index(op.f('idx_tm_finance_entries_tipo'), 'tm_finance_entries', ['tipo'], unique=False)
    op.create_index(op.f('idx_tm_finance_entries_status'), 'tm_finance_entries', ['status'], unique=False)
    op.create_index(op.f('idx_tm_finance_entries_freight_id'), 'tm_finance_entries', ['freight_id'], unique=False)
    op.create_index(op.f('idx_tm_finance_entries_deleted_at'), 'tm_finance_entries', ['deleted_at'], unique=False)
    op.alter_column('tm_finance_entries', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('tm_finance_entries', 'status',
               existing_type=postgresql.ENUM('pendente', 'pago', 'cancelado', 'vencido', name='financeentrystatus'),
               server_default=sa.text("'pendente'::financeentrystatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_tm_drivers_user_id'), table_name='tm_drivers')
    op.drop_index(op.f('ix_tm_drivers_deleted_at'), table_name='tm_drivers')
    op.drop_index(op.f('ix_tm_drivers_cpf'), table_name='tm_drivers')
    op.create_unique_constraint(op.f('tm_drivers_cpf_key'), 'tm_drivers', ['cpf'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tm_drivers_user_id'), 'tm_drivers', ['user_id'], unique=False)
    op.create_index(op.f('idx_tm_drivers_deleted_at'), 'tm_drivers', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_tm_drivers_cpf'), 'tm_drivers', ['cpf'], unique=False)
    op.alter_column('tm_drivers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('tm_drivers', 'status',
               existing_type=postgresql.ENUM('ativo', 'inativo', 'suspenso', 'ferias', name='driverstatus'),
               server_default=sa.text("'ativo'::driverstatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_tm_clients_deleted_at'), table_name='tm_clients')
    op.drop_index(op.f('ix_tm_clients_cpf_cnpj'), table_name='tm_clients')
    op.create_unique_constraint(op.f('tm_clients_cpf_cnpj_key'), 'tm_clients', ['cpf_cnpj'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tm_clients_nome_trgm'), 'tm_clients', ['nome'], unique=False, postgresql_ops={'nome': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_tm_clients_deleted_at'), 'tm_clients', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_tm_clients_cpf_cnpj'), 'tm_clients', ['cpf_cnpj'], unique=False)
    op.alter_column('tm_clients', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('tm_clients', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('tm_clients', 'endereco',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('produtos_cardapio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('disponivel', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('produtos_cardapio_pkey'))
    )
    op.create_table('ingredientes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ingredientes_pkey')),
    sa.UniqueConstraint('nome', name=op.f('ingredientes_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preco_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('itens_pedido_pedido_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_cardapio.id'], name=op.f('itens_pedido_produto_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('itens_pedido_pkey'))
    )
    op.create_table('item_ingrediente_removido',
    sa.Column('item_pedido_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingrediente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], name=op.f('item_ingrediente_removido_ingrediente_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_pedido_id'], ['itens_pedido.id'], name=op.f('item_ingrediente_removido_item_pedido_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_pedido_id', 'ingrediente_id', name=op.f('item_ingrediente_removido_pkey'))
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('contacts_pkey')),
    sa.UniqueConstraint('phone', name=op.f('contacts_phone_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('senha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('email', name=op.f('usuarios_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('persons',
    sa.Column('personid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('personid', name=op.f('persons_pkey'))
    )
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('pedidos_usuario_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pedidos_pkey'))
    )
    op.create_table('produto_ingrediente',
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingrediente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], name=op.f('produto_ingrediente_ingrediente_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_cardapio.id'], name=op.f('produto_ingrediente_produto_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('produto_id', 'ingrediente_id', name=op.f('produto_ingrediente_pkey'))
    )
    # ### end Alembic commands ###
